# Generated by Django 3.2 on 2021-10-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0002_alter_useraccounts_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='User_id',
            field=models.CharField(max_length=255),
        ),
    ]
