# Generated by Django 3.2 on 2021-10-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0004_auto_20211019_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='food_old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='food_rate_per_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
