# Generated by Django 3.2 on 2021-10-22 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0005_auto_20211019_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('food_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=25)),
                ('quantity', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=25)),
                ('qrcode_image', models.ImageField(upload_to='qrcodes/')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('needed_date', models.DateTimeField()),
                ('purchasing_time', models.IntegerField()),
                ('payment_successful', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
