# Generated by Django 3.2 on 2021-10-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0007_auto_20211028_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_list',
            field=models.JSONField(default={}),
        ),
    ]
