# Generated by Django 3.2 on 2021-10-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0009_alter_orders_order_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total_cost',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='orders',
            name='no_of_items',
            field=models.IntegerField(default=0),
        ),
    ]
