# Generated by Django 3.2 on 2021-10-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0010_auto_20211028_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='needed_date',
            new_name='purchasing_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='purchasing_time',
        ),
    ]
