# Generated by Django 3.2 on 2021-10-29 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0011_auto_20211028_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
