# Generated by Django 3.2 on 2021-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0012_alter_orders_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qrcode_image',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
