# Generated by Django 3.2 on 2021-10-29 14:06

import ModelView.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0013_alter_orders_qrcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qrcode_image',
            field=models.ImageField(blank=True, default='', upload_to=ModelView.models.upload_path),
        ),
    ]
