# Generated by Django 3.2 on 2021-10-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0014_alter_orders_qrcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='purchased_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
