# Generated by Django 3.2 on 2021-11-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0017_alter_orders_purchased_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='handover_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_available_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_handovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='is_prepared',
            field=models.BooleanField(default=False),
        ),
    ]
