# Generated by Django 3.2 on 2021-11-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0018_auto_20211101_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_handovered',
        ),
    ]
