# Generated by Django 3.2 on 2021-11-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0019_remove_orders_is_handovered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='Address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='pincode',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
