# Generated by Django 3.2 on 2021-11-04 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0020_auto_20211104_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('search_name', models.CharField(max_length=255)),
                ('search_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Alert',
            },
        ),
        migrations.AddField(
            model_name='useraccounts',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
