# Generated by Django 3.2 on 2021-11-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0021_auto_20211104_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='profile_image',
            field=models.ImageField(blank=True, default='Media/users/userSnackBar2021.png', upload_to='Media/users/'),
        ),
    ]
