# Generated by Django 3.2 on 2021-11-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0024_alter_useraccounts_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
    ]
