# Generated by Django 3.2 on 2021-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0029_notifications_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='notifications/'),
        ),
    ]
