# Generated by Django 3.2 on 2021-11-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0031_alter_notifications_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='food_total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
