# Generated by Django 3.2 on 2021-11-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelView', '0032_fooditems_food_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='expiry_days_count',
            field=models.IntegerField(default=0),
        ),
    ]
